import Foundation

// MARK: - Client Options

/// Configuration options for SiloClient.
public struct SiloClientOptions: Sendable {
    /// Base URL of the Silo API (e.g. "https://api.silo.geekapps.io").
    public var baseUrl: String
    /// Optional URL for the Silo viewer app (used to build view URLs).
    public var appUrl: String?
    /// Bearer token for authentication.
    public var token: String?
    /// Default bucket slug used when no bucket is specified in upload calls.
    public var defaultBucket: String?

    public init(
        baseUrl: String,
        appUrl: String? = nil,
        token: String? = nil,
        defaultBucket: String? = nil
    ) {
        self.baseUrl = baseUrl
        self.appUrl = appUrl
        self.token = token
        self.defaultBucket = defaultBucket
    }
}

// MARK: - File Models

/// Represents a variant/rendition of a file (e.g. different resolution or format).
public struct SiloFileVariant: Codable, Sendable {
    public let id: String
    public let key: String
    public let bucket: String
    public let url: String?
    public let mimeType: String?
    public let size: Int?
    public let width: Int?
    public let height: Int?
    public let bitrate: Int?
    public let codec: String?
    public let label: String?
    public let createdAt: Date?

    public init(
        id: String, key: String, bucket: String, url: String? = nil,
        mimeType: String? = nil, size: Int? = nil, width: Int? = nil,
        height: Int? = nil, bitrate: Int? = nil, codec: String? = nil,
        label: String? = nil, createdAt: Date? = nil
    ) {
        self.id = id; self.key = key; self.bucket = bucket; self.url = url
        self.mimeType = mimeType; self.size = size; self.width = width
        self.height = height; self.bitrate = bitrate; self.codec = codec
        self.label = label; self.createdAt = createdAt
    }
}

/// Metadata associated with a file (dimensions, duration, etc.).
public struct SiloFileMetadata: Codable, Sendable {
    public let width: Int?
    public let height: Int?
    public let duration: Double?
    public let bitrate: Int?
    public let fps: Double?
    public let codec: String?
    public let audioCodec: String?
    public let audioChannels: Int?
    public let format: String?
    public let hasAudio: Bool?
    public let hasVideo: Bool?
    public let isHdr: Bool?
    public let colorSpace: String?
    public let rotation: Int?
    public let aspectRatio: String?
    public let thumbnailCount: Int?
    public let storyboardCount: Int?

    public init(
        width: Int? = nil, height: Int? = nil, duration: Double? = nil,
        bitrate: Int? = nil, fps: Double? = nil, codec: String? = nil,
        audioCodec: String? = nil, audioChannels: Int? = nil,
        format: String? = nil, hasAudio: Bool? = nil, hasVideo: Bool? = nil,
        isHdr: Bool? = nil, colorSpace: String? = nil, rotation: Int? = nil,
        aspectRatio: String? = nil, thumbnailCount: Int? = nil,
        storyboardCount: Int? = nil
    ) {
        self.width = width; self.height = height; self.duration = duration
        self.bitrate = bitrate; self.fps = fps; self.codec = codec
        self.audioCodec = audioCodec; self.audioChannels = audioChannels
        self.format = format; self.hasAudio = hasAudio; self.hasVideo = hasVideo
        self.isHdr = isHdr; self.colorSpace = colorSpace; self.rotation = rotation
        self.aspectRatio = aspectRatio; self.thumbnailCount = thumbnailCount
        self.storyboardCount = storyboardCount
    }
}

/// A caption/subtitle track attached to a file.
public struct SiloFileCaption: Codable, Sendable {
    public let id: String
    public let language: String
    public let label: String?
    public let url: String?
    public let isAutoGenerated: Bool?
    public let createdAt: Date?

    public init(
        id: String, language: String, label: String? = nil,
        url: String? = nil, isAutoGenerated: Bool? = nil, createdAt: Date? = nil
    ) {
        self.id = id; self.language = language; self.label = label
        self.url = url; self.isAutoGenerated = isAutoGenerated
        self.createdAt = createdAt
    }
}

/// An audio track attached to a file.
public struct SiloFileAudioTrack: Codable, Sendable {
    public let id: String
    public let label: String?
    public let language: String?
    public let codec: String?
    public let channels: Int?
    public let isAtmos: Bool?
    public let isDefault: Bool?

    public init(
        id: String, label: String? = nil, language: String? = nil,
        codec: String? = nil, channels: Int? = nil,
        isAtmos: Bool? = nil, isDefault: Bool? = nil
    ) {
        self.id = id; self.label = label; self.language = language
        self.codec = codec; self.channels = channels
        self.isAtmos = isAtmos; self.isDefault = isDefault
    }
}

/// The main Silo file object returned from the API.
public struct SiloFile: Codable, Sendable {
    public let id: String
    public let key: String
    public let bucket: String
    public let url: String?
    public let directUrl: String?
    public let mimeType: String?
    public let size: Int?
    public let status: String?
    public let category: String?
    public let title: String?
    public let description: String?
    public let tags: [String]?
    public let isPrivate: Bool?
    public let expiresAt: Date?
    public let createdAt: Date?
    public let updatedAt: Date?
    public let metadata: SiloFileMetadata?
    public let variants: [SiloFileVariant]?
    public let captions: [SiloFileCaption]?
    public let audioTracks: [SiloFileAudioTrack]?
    public let hlsUrl: String?
    public let thumbnailUrl: String?
    public let storyboardUrl: String?
    public let rawVideoUrl: String?
    public let rawImageUrl: String?
    public let viewerQuery: String?

    public init(
        id: String, key: String, bucket: String, url: String? = nil,
        directUrl: String? = nil, mimeType: String? = nil, size: Int? = nil,
        status: String? = nil, category: String? = nil, title: String? = nil,
        description: String? = nil, tags: [String]? = nil,
        isPrivate: Bool? = nil, expiresAt: Date? = nil,
        createdAt: Date? = nil, updatedAt: Date? = nil,
        metadata: SiloFileMetadata? = nil, variants: [SiloFileVariant]? = nil,
        captions: [SiloFileCaption]? = nil, audioTracks: [SiloFileAudioTrack]? = nil,
        hlsUrl: String? = nil, thumbnailUrl: String? = nil,
        storyboardUrl: String? = nil, rawVideoUrl: String? = nil,
        rawImageUrl: String? = nil, viewerQuery: String? = nil
    ) {
        self.id = id; self.key = key; self.bucket = bucket; self.url = url
        self.directUrl = directUrl; self.mimeType = mimeType; self.size = size
        self.status = status; self.category = category; self.title = title
        self.description = description; self.tags = tags
        self.isPrivate = isPrivate; self.expiresAt = expiresAt
        self.createdAt = createdAt; self.updatedAt = updatedAt
        self.metadata = metadata; self.variants = variants
        self.captions = captions; self.audioTracks = audioTracks
        self.hlsUrl = hlsUrl; self.thumbnailUrl = thumbnailUrl
        self.storyboardUrl = storyboardUrl; self.rawVideoUrl = rawVideoUrl
        self.rawImageUrl = rawImageUrl; self.viewerQuery = viewerQuery
    }
}

// MARK: - Upload Models

/// Result returned after a completed upload.
public struct UploadResult: Codable, Sendable {
    public let id: String
    public let key: String
    public let bucket: String
    public let url: String?
    public let directUrl: String?
    public let mimeType: String?
    public let size: Int?
    public let status: String?
    public let category: String?

    public init(
        id: String, key: String, bucket: String, url: String? = nil,
        directUrl: String? = nil, mimeType: String? = nil,
        size: Int? = nil, status: String? = nil, category: String? = nil
    ) {
        self.id = id; self.key = key; self.bucket = bucket
        self.url = url; self.directUrl = directUrl; self.mimeType = mimeType
        self.size = size; self.status = status; self.category = category
    }
}

/// Signed URL result from the API.
public struct SignedUrlResult: Codable, Sendable {
    public let url: String
    public let expiresIn: Int?
    public let viewerQuery: String?

    public init(url: String, expiresIn: Int? = nil, viewerQuery: String? = nil) {
        self.url = url; self.expiresIn = expiresIn; self.viewerQuery = viewerQuery
    }
}

// MARK: - Upload Options

/// Options for image uploads.
public struct ImageUploadOptions: Codable, Sendable {
    /// Convert/optimize the image on the server side.
    public var optimize: Bool?
    /// Target output format (e.g. "webp", "jpeg", "png").
    public var format: String?
    /// Upload as a raw (unprocessed) image.
    public var raw: Bool?

    public init(optimize: Bool? = nil, format: String? = nil, raw: Bool? = nil) {
        self.optimize = optimize; self.format = format; self.raw = raw
    }
}

/// Options for video uploads.
public struct VideoUploadOptions: Codable, Sendable {
    /// Generate video thumbnails.
    public var thumbnails: Bool?
    /// Generate a storyboard preview strip.
    public var storyboard: Bool?
    /// Auto-generate captions via speech recognition.
    public var autoCaptions: Bool?
    /// Languages for caption generation (e.g. ["en", "pt"]).
    public var languages: [String]?
    /// Target video codec (e.g. "h264", "h265", "av1").
    public var codec: String?
    /// Transcoding profile: pass specific profile names or "auto".
    public var transcoding: [String]?
    /// Run AI enrichment on the video.
    public var enrich: Bool?
    /// Target audio codec (e.g. "aac", "opus").
    public var audioCodec: String?
    /// Audio channel layout (e.g. "stereo", "5.1").
    public var audioChannels: String?
    /// Preserve Dolby Atmos audio.
    public var preserveAtmos: Bool?
    /// HDR handling ("preserve", "convert", "strip").
    public var hdr: String?
    /// Upload as a raw (unprocessed) video.
    public var raw: Bool?

    public init(
        thumbnails: Bool? = nil, storyboard: Bool? = nil,
        autoCaptions: Bool? = nil, languages: [String]? = nil,
        codec: String? = nil, transcoding: [String]? = nil,
        enrich: Bool? = nil, audioCodec: String? = nil,
        audioChannels: String? = nil, preserveAtmos: Bool? = nil,
        hdr: String? = nil, raw: Bool? = nil
    ) {
        self.thumbnails = thumbnails; self.storyboard = storyboard
        self.autoCaptions = autoCaptions; self.languages = languages
        self.codec = codec; self.transcoding = transcoding
        self.enrich = enrich; self.audioCodec = audioCodec
        self.audioChannels = audioChannels; self.preserveAtmos = preserveAtmos
        self.hdr = hdr; self.raw = raw
    }
}

// MARK: - Multipart Upload

/// Options for starting a multipart upload.
public struct MultipartStartOptions: Codable, Sendable {
    public var fileName: String
    public var mimeType: String
    public var size: Int?
    public var bucket: String?
    public var expiresIn: Int?
    public var isPrivate: Bool?
    public var title: String?
    public var description: String?
    public var tags: [String]?
    public var image: ImageUploadOptions?
    public var video: VideoUploadOptions?

    public init(
        fileName: String, mimeType: String, size: Int? = nil,
        bucket: String? = nil, expiresIn: Int? = nil,
        isPrivate: Bool? = nil, title: String? = nil,
        description: String? = nil, tags: [String]? = nil,
        image: ImageUploadOptions? = nil, video: VideoUploadOptions? = nil
    ) {
        self.fileName = fileName; self.mimeType = mimeType; self.size = size
        self.bucket = bucket; self.expiresIn = expiresIn
        self.isPrivate = isPrivate; self.title = title
        self.description = description; self.tags = tags
        self.image = image; self.video = video
    }
}

/// Result from starting a multipart upload session.
public struct MultipartStartResult: Codable, Sendable {
    public let fileId: String
    public let uploadId: String
    public let s3Key: String

    public init(fileId: String, uploadId: String, s3Key: String) {
        self.fileId = fileId; self.uploadId = uploadId; self.s3Key = s3Key
    }
}

/// A presigned URL for uploading a single part.
public struct MultipartPartUrl: Codable, Sendable {
    public let url: String
    public let partNumber: Int

    public init(url: String, partNumber: Int) {
        self.url = url; self.partNumber = partNumber
    }
}

/// A completed multipart part descriptor (sent to complete the upload).
public struct MultipartPart: Codable, Sendable {
    /// Part number (1-based).
    public let partNumber: Int
    /// ETag returned by S3 after the part upload.
    public let eTag: String

    public init(partNumber: Int, eTag: String) {
        self.partNumber = partNumber; self.eTag = eTag
    }

    private enum CodingKeys: String, CodingKey {
        case partNumber = "PartNumber"
        case eTag = "ETag"
    }
}

// MARK: - Batch Upload

/// Options for starting a batch upload.
public struct BatchStartOptions: Codable, Sendable {
    public var files: [BatchFileEntry]
    public var bucket: String?
    public var video: VideoUploadOptions?
    public var image: ImageUploadOptions?

    public init(
        files: [BatchFileEntry], bucket: String? = nil,
        video: VideoUploadOptions? = nil, image: ImageUploadOptions? = nil
    ) {
        self.files = files; self.bucket = bucket
        self.video = video; self.image = image
    }
}

/// A single file entry in a batch upload request.
public struct BatchFileEntry: Codable, Sendable {
    public var fileName: String
    public var mimeType: String
    public var size: Int?

    public init(fileName: String, mimeType: String, size: Int? = nil) {
        self.fileName = fileName; self.mimeType = mimeType; self.size = size
    }
}

/// Result after starting a batch upload.
public struct BatchStartResult: Codable, Sendable {
    public let batchId: String
    public let items: [BatchUploadItem]

    public init(batchId: String, items: [BatchUploadItem]) {
        self.batchId = batchId; self.items = items
    }
}

/// Status of an ongoing batch upload.
public struct BatchStatus: Codable, Sendable {
    public let batchId: String
    public let status: String
    public let items: [BatchUploadItem]
    public let createdAt: Date?
    public let updatedAt: Date?

    public init(
        batchId: String, status: String, items: [BatchUploadItem],
        createdAt: Date? = nil, updatedAt: Date? = nil
    ) {
        self.batchId = batchId; self.status = status; self.items = items
        self.createdAt = createdAt; self.updatedAt = updatedAt
    }
}

/// A single item within a batch upload.
public struct BatchUploadItem: Codable, Sendable {
    public let fileId: String?
    public let uploadId: String?
    public let s3Key: String?
    public let fileName: String?
    public let mimeType: String?
    public let status: String?
    public let uploadUrl: String?

    public init(
        fileId: String? = nil, uploadId: String? = nil,
        s3Key: String? = nil, fileName: String? = nil,
        mimeType: String? = nil, status: String? = nil,
        uploadUrl: String? = nil
    ) {
        self.fileId = fileId; self.uploadId = uploadId; self.s3Key = s3Key
        self.fileName = fileName; self.mimeType = mimeType
        self.status = status; self.uploadUrl = uploadUrl
    }
}

// MARK: - Bucket Models

/// Represents a Silo storage bucket.
public struct SiloBucket: Codable, Sendable {
    public let id: String
    public let name: String
    public let slug: String
    public let visibility: String?
    public let fileCount: Int?
    public let totalSize: Int?
    public let createdAt: Date?
    public let updatedAt: Date?

    public init(
        id: String, name: String, slug: String, visibility: String? = nil,
        fileCount: Int? = nil, totalSize: Int? = nil,
        createdAt: Date? = nil, updatedAt: Date? = nil
    ) {
        self.id = id; self.name = name; self.slug = slug
        self.visibility = visibility; self.fileCount = fileCount
        self.totalSize = totalSize; self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

/// Paginated list of buckets.
public struct ListBucketsResult: Codable, Sendable {
    public let buckets: [SiloBucket]
    public let total: Int?
    public let cursor: String?

    public init(buckets: [SiloBucket], total: Int? = nil, cursor: String? = nil) {
        self.buckets = buckets; self.total = total; self.cursor = cursor
    }
}

/// Paginated list of files.
public struct ListFilesResult: Codable, Sendable {
    public let files: [SiloFile]
    public let total: Int?
    public let cursor: String?

    public init(files: [SiloFile], total: Int? = nil, cursor: String? = nil) {
        self.files = files; self.total = total; self.cursor = cursor
    }
}

// MARK: - Ratings

/// Aggregate reaction counts for a file.
public struct AggregateRating: Codable, Sendable {
    public let fileId: String
    public let love: Int
    public let like: Int
    public let dislike: Int

    private enum CodingKeys: String, CodingKey {
        case fileId
        case love = "LOVE"
        case like = "LIKE"
        case dislike = "DISLIKE"
    }

    public init(fileId: String, love: Int, like: Int, dislike: Int) {
        self.fileId = fileId; self.love = love
        self.like = like; self.dislike = dislike
    }
}

// MARK: - Age Ratings

/// An age/content rating entry.
public struct SiloAgeRating: Codable, Sendable {
    public let id: String
    public let label: String
    public let description: String?
    public let region: String?
    public let minAge: Int?
    public let icon: String?

    public init(
        id: String, label: String, description: String? = nil,
        region: String? = nil, minAge: Int? = nil, icon: String? = nil
    ) {
        self.id = id; self.label = label; self.description = description
        self.region = region; self.minAge = minAge; self.icon = icon
    }
}

// MARK: - Dashboard

/// Quota information for the organisation.
public struct OrgQuota: Codable, Sendable {
    public let storageUsed: Int?
    public let storageLimit: Int?
    public let bandwidthUsed: Int?
    public let bandwidthLimit: Int?
    public let fileCount: Int?
    public let fileLimit: Int?

    public init(
        storageUsed: Int? = nil, storageLimit: Int? = nil,
        bandwidthUsed: Int? = nil, bandwidthLimit: Int? = nil,
        fileCount: Int? = nil, fileLimit: Int? = nil
    ) {
        self.storageUsed = storageUsed; self.storageLimit = storageLimit
        self.bandwidthUsed = bandwidthUsed; self.bandwidthLimit = bandwidthLimit
        self.fileCount = fileCount; self.fileLimit = fileLimit
    }
}

/// Top-level dashboard data.
public struct DashboardData: Codable, Sendable {
    public let quota: OrgQuota?
    public let recentFiles: [SiloFile]?
    public let buckets: [SiloBucket]?
    public let stats: [String: Int]?

    public init(
        quota: OrgQuota? = nil, recentFiles: [SiloFile]? = nil,
        buckets: [SiloBucket]? = nil, stats: [String: Int]? = nil
    ) {
        self.quota = quota; self.recentFiles = recentFiles
        self.buckets = buckets; self.stats = stats
    }
}
